package com.tts.subscriberlist;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import org.hibernate.annotations.CreationTimestamp;

@Entity
public class Subscriber {
	
	public interface SubscriberRepository {

	}

// sets the "id" as the primary key
@Id
	// allows the id to be generated by the underlying database
@GeneratedValue(strategy=GenerationType.AUTO)
	private Long id;

	private String firstName;
	private String lastName;

	
	
	
	

@Column
	// allows the date to be generated by the system
@CreationTimestamp
	private Date signedUp;

	
    public Subscriber(String firstName, String lastName, String userName, Date signedUp, String emailName){
	// non-argument constructor needed for JPA
    	
    this.firstName = firstName;
	this.lastName = lastName;
	this.signedUp = signedUp;

    }
	public Subscriber(String firstName2, String lastName2, Date signedUp2) {
		// TODO Auto-generated constructor stub
	}
	public Long getId() {
		return id;
	}


	public void setId(Long id) {
		this.id = id;
	}


	public String getFirstName() {
		return firstName;
	}


	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}


	public String getLastName() {
		return lastName;
	}


	public void setLastName(String lastName) {
		this.lastName = lastName;
	}


	public Date getSignedUp() {
		return signedUp;
	}


	public void setSignedUp(Date signedUp) {
		this.signedUp = signedUp;
	}
	@Override
	public String toString() {
		return "Subscriber [id=" + id + ", firstName=" + firstName + ", lastName=" + lastName + ", signedUp=" + signedUp
				+ ", getId()=" + getId() + ", getFirstName()=" + getFirstName() + ", getLastName()=" + getLastName()
				+ ", getSignedUp()=" + getSignedUp() + ", getClass()=" + getClass() + ", hashCode()=" + hashCode()
				+ ", toString()=" + super.toString() + "]";
	}
	public void save(Subscriber subscriber) {
		// TODO Auto-generated method stub
		
	}
	
}
